/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DemoIfAdaptor -a demoifadaptor.h:demoifadaptor.cpp com.nokia.Demo.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "demoifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DemoIfAdaptor
 */

DemoIfAdaptor::DemoIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    qDebug()<<"server::DemoIfAdaptor constructor";
    /*
     * setAutoRelaySignals is must as it
     * connect signal to sinal i.e.
     * when the function of proxy/client is called
     * function with same name as the proxy/client of adaptor is also called.
     *read from help
    */
    setAutoRelaySignals(true);
}

DemoIfAdaptor::~DemoIfAdaptor()
{
    qDebug()<<"server::DemoIfAdaptor destructor";
}

void DemoIfAdaptor::SayBye()
{
    // handle method call com.nokia.Demo.SayBye
    qDebug()<<"server::SayBye 1";
    //QMetaObject::invokeMethod(parent(), "SayBye");
    qDebug()<<"server::SayBye 2";
}

void DemoIfAdaptor::SayHello(const QString &name, const QVariantMap &customdata)
{
    // handle method call com.nokia.Demo.SayHello
     qDebug()<<"server::SayHello(const QString &name, const QVariantMap &customdata) 1";
     /*
      *QMetaObject::invokeMethod it is used to called the method SayHello of class MyDemo
      * as it is auto generated file so what we have to do in SayHello is written in class MyDemo
      *
      * */
    QMetaObject::invokeMethod(parent(), "SayHello", Q_ARG(QString, name), Q_ARG(QVariantMap, customdata));
     qDebug()<<"server::SayHello(const QString &name, const QVariantMap &customdata) 2";
}

